language: node_js
node_js:
  - "iojs"
  - "6"
addons:
  apt:
    sources:
    - mongodb-org-tools
services:
  - mongodb
env:
  - NODE_ENV=test
script:
  - mongoimport --db nasihat --collection nasihats --type json --file nasihat.json